name: All Well And Good
favicon: null
layout_spectrum: 0.7937747149262577
typography_spectrum: 0.6470070951618254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.6855937377549708
  lightness: 0.41350167407654226
  saturation: 0.5562099830713123
  rhythmicContrast: 0.3658707947470248
purpose: []
